#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : nagios-plugins
Version  : 2.4.10
Release  : 13
URL      : https://nagios-plugins.org/download/nagios-plugins-2.4.10.tar.gz
Source0  : https://nagios-plugins.org/download/nagios-plugins-2.4.10.tar.gz
Summary  : Host/service/network monitoring program plugins for Nagios
Group    : Development/Tools
License  : GPL-3.0
Requires: nagios-plugins-libexec = %{version}-%{release}
Requires: nagios-plugins-license = %{version}-%{release}
Requires: nagios-plugins-locales = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : glibc-locale
BuildRequires : gnutls-dev
BuildRequires : krb5-dev
BuildRequires : mariadb-dev
BuildRequires : openldap-dev
BuildRequires : openssl-dev
BuildRequires : procps-ng
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Nagios is a program that will monitor hosts and services on your
network, and to email or page you when a problem arises or is
resolved. Nagios runs on a unix server as a background or daemon
process, intermittently running checks on various services that you
specify. The actual service checks are performed by separate "plugin"
programs which return the status of the checks to Nagios. This package
contains those plugins.

%package extras
Summary: extras components for the nagios-plugins package.
Group: Default

%description extras
extras components for the nagios-plugins package.


%package libexec
Summary: libexec components for the nagios-plugins package.
Group: Default
Requires: nagios-plugins-license = %{version}-%{release}

%description libexec
libexec components for the nagios-plugins package.


%package license
Summary: license components for the nagios-plugins package.
Group: Default

%description license
license components for the nagios-plugins package.


%package locales
Summary: locales components for the nagios-plugins package.
Group: Default

%description locales
locales components for the nagios-plugins package.


%prep
%setup -q -n nagios-plugins-2.4.10
cd %{_builddir}/nagios-plugins-2.4.10
pushd ..
cp -a nagios-plugins-2.4.10 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719979424
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719979424
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nagios-plugins
cp %{_builddir}/nagios-plugins-%{version}/COPYING %{buildroot}/usr/share/package-licenses/nagios-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang nagios-plugins
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files extras
%defattr(-,root,root,-)
/usr/libexec/check_breeze
/usr/libexec/check_disk_smb
/usr/libexec/check_file_age
/usr/libexec/check_flexlm
/usr/libexec/check_ifoperstatus
/usr/libexec/check_ifstatus
/usr/libexec/check_ircd
/usr/libexec/check_mailq
/usr/libexec/check_rpc
/usr/libexec/check_wave

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/check_apt
/V3/usr/libexec/check_cluster
/V3/usr/libexec/check_disk
/V3/usr/libexec/check_dummy
/V3/usr/libexec/check_http
/V3/usr/libexec/check_ide_smart
/V3/usr/libexec/check_ldap
/V3/usr/libexec/check_load
/V3/usr/libexec/check_mrtg
/V3/usr/libexec/check_mrtgtraf
/V3/usr/libexec/check_mysql
/V3/usr/libexec/check_mysql_query
/V3/usr/libexec/check_nagios
/V3/usr/libexec/check_nt
/V3/usr/libexec/check_ntp
/V3/usr/libexec/check_ntp_peer
/V3/usr/libexec/check_ntp_time
/V3/usr/libexec/check_nwstat
/V3/usr/libexec/check_overcr
/V3/usr/libexec/check_ping
/V3/usr/libexec/check_procs
/V3/usr/libexec/check_real
/V3/usr/libexec/check_smtp
/V3/usr/libexec/check_ssh
/V3/usr/libexec/check_swap
/V3/usr/libexec/check_tcp
/V3/usr/libexec/check_time
/V3/usr/libexec/check_ups
/V3/usr/libexec/check_uptime
/V3/usr/libexec/check_users
/V3/usr/libexec/negate
/V3/usr/libexec/remove_perfdata
/V3/usr/libexec/urlize
/usr/libexec/check_apt
/usr/libexec/check_clamd
/usr/libexec/check_cluster
/usr/libexec/check_disk
/usr/libexec/check_dummy
/usr/libexec/check_ftp
/usr/libexec/check_http
/usr/libexec/check_ide_smart
/usr/libexec/check_imap
/usr/libexec/check_jabber
/usr/libexec/check_ldap
/usr/libexec/check_ldaps
/usr/libexec/check_load
/usr/libexec/check_log
/usr/libexec/check_mrtg
/usr/libexec/check_mrtgtraf
/usr/libexec/check_mysql
/usr/libexec/check_mysql_query
/usr/libexec/check_nagios
/usr/libexec/check_nntp
/usr/libexec/check_nntps
/usr/libexec/check_nt
/usr/libexec/check_ntp
/usr/libexec/check_ntp_peer
/usr/libexec/check_ntp_time
/usr/libexec/check_nwstat
/usr/libexec/check_oracle
/usr/libexec/check_overcr
/usr/libexec/check_ping
/usr/libexec/check_pop
/usr/libexec/check_procs
/usr/libexec/check_real
/usr/libexec/check_sensors
/usr/libexec/check_simap
/usr/libexec/check_smtp
/usr/libexec/check_spop
/usr/libexec/check_ssh
/usr/libexec/check_ssl_validity
/usr/libexec/check_ssmtp
/usr/libexec/check_swap
/usr/libexec/check_tcp
/usr/libexec/check_time
/usr/libexec/check_udp
/usr/libexec/check_ups
/usr/libexec/check_uptime
/usr/libexec/check_users
/usr/libexec/negate
/usr/libexec/remove_perfdata
/usr/libexec/urlize
/usr/libexec/utils.pm
/usr/libexec/utils.sh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nagios-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files locales -f nagios-plugins.lang
%defattr(-,root,root,-)

