#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nagios-plugins
Version  : 2.3.3
Release  : 10
URL      : https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
Source0  : https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
Summary  : Host/service/network monitoring program plugins for Nagios
Group    : Development/Tools
License  : GPL-3.0
Requires: nagios-plugins-libexec = %{version}-%{release}
Requires: nagios-plugins-license = %{version}-%{release}
Requires: nagios-plugins-locales = %{version}-%{release}
BuildRequires : glibc-locale
BuildRequires : gnutls-dev
BuildRequires : krb5-dev
BuildRequires : mariadb-dev
BuildRequires : openldap-dev
BuildRequires : openssl-dev
BuildRequires : procps-ng

%description
Nagios is a program that will monitor hosts and services on your
network, and to email or page you when a problem arises or is
resolved. Nagios runs on a unix server as a background or daemon
process, intermittently running checks on various services that you
specify. The actual service checks are performed by separate "plugin"
programs which return the status of the checks to Nagios. This package
contains those plugins.

%package extras
Summary: extras components for the nagios-plugins package.
Group: Default

%description extras
extras components for the nagios-plugins package.


%package libexec
Summary: libexec components for the nagios-plugins package.
Group: Default
Requires: nagios-plugins-license = %{version}-%{release}

%description libexec
libexec components for the nagios-plugins package.


%package license
Summary: license components for the nagios-plugins package.
Group: Default

%description license
license components for the nagios-plugins package.


%package locales
Summary: locales components for the nagios-plugins package.
Group: Default

%description locales
locales components for the nagios-plugins package.


%prep
%setup -q -n nagios-plugins-2.3.3
cd %{_builddir}/nagios-plugins-2.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1605725711
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1605725711
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nagios-plugins
cp %{_builddir}/nagios-plugins-2.3.3/COPYING %{buildroot}/usr/share/package-licenses/nagios-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install
%find_lang nagios-plugins

%files
%defattr(-,root,root,-)

%files extras
%defattr(-,root,root,-)
/usr/libexec/check_breeze
/usr/libexec/check_disk_smb
/usr/libexec/check_file_age
/usr/libexec/check_flexlm
/usr/libexec/check_ifoperstatus
/usr/libexec/check_ifstatus
/usr/libexec/check_ircd
/usr/libexec/check_mailq
/usr/libexec/check_rpc
/usr/libexec/check_wave

%files libexec
%defattr(-,root,root,-)
/usr/libexec/check_apt
/usr/libexec/check_clamd
/usr/libexec/check_cluster
/usr/libexec/check_disk
/usr/libexec/check_dummy
/usr/libexec/check_ftp
/usr/libexec/check_http
/usr/libexec/check_ide_smart
/usr/libexec/check_imap
/usr/libexec/check_jabber
/usr/libexec/check_ldap
/usr/libexec/check_ldaps
/usr/libexec/check_load
/usr/libexec/check_log
/usr/libexec/check_mrtg
/usr/libexec/check_mrtgtraf
/usr/libexec/check_mysql
/usr/libexec/check_mysql_query
/usr/libexec/check_nagios
/usr/libexec/check_nntp
/usr/libexec/check_nntps
/usr/libexec/check_nt
/usr/libexec/check_ntp
/usr/libexec/check_ntp_peer
/usr/libexec/check_ntp_time
/usr/libexec/check_nwstat
/usr/libexec/check_oracle
/usr/libexec/check_overcr
/usr/libexec/check_ping
/usr/libexec/check_pop
/usr/libexec/check_procs
/usr/libexec/check_real
/usr/libexec/check_sensors
/usr/libexec/check_simap
/usr/libexec/check_smtp
/usr/libexec/check_spop
/usr/libexec/check_ssh
/usr/libexec/check_ssl_validity
/usr/libexec/check_ssmtp
/usr/libexec/check_swap
/usr/libexec/check_tcp
/usr/libexec/check_time
/usr/libexec/check_udp
/usr/libexec/check_ups
/usr/libexec/check_uptime
/usr/libexec/check_users
/usr/libexec/negate
/usr/libexec/remove_perfdata
/usr/libexec/urlize
/usr/libexec/utils.pm
/usr/libexec/utils.sh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nagios-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files locales -f nagios-plugins.lang
%defattr(-,root,root,-)

